apiVersion: v1
entries:
  http-server:
  - apiVersion: v2
    created: "2022-02-10T19:25:44.455584+01:00"
    digest: 879e7e801dbbdd89619527f58a349c353d2d1bcda30992bd36ed11db6c294ff6
    name: http-server
    type: application
    urls:
    - https://colab-coop.github.io/helm-charts/charts/http-server-0.0.1.tgz
    version: 0.0.1
generated: "2022-02-10T19:25:44.45473+01:00"
