issuer: "letsencrypt-prod"

hosts:
  - host1.example.com
  - host2.example.com

# disk:
#   size: 20Gi
#   mountPath: /opt/data

# backup:
#   schedule: "0 * * * *"
#   ttl: "720h"

image:
  tag: gcr.io/kuar-demo/kuard-amd64:1
  port: 8080
#  env:
#     SOME_ENV: some-value

imageCredentials:
  registry: https://index.docker.io/v1/
  # username: {{ requiredEnv "DOCKER_USER" }}
  # password: {{ requiredEnv "DOCKER_PASSWORD" }}
  # email: email@example.com
