apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{- if .Values.backup }}
      {{- if .Values.disk }}
      annotations:
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "{{ .Values.disk.mountPath }}"]'
        pre.hook.backup.velero.io/container: "fsfreeze"
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "{{ .Values.disk.mountPath }}"]'
        post.hook.backup.velero.io/container: "fsfreeze"
      {{- end }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.image.port }}
        {{- if .Values.image.env }}
        env:
          {{- range $key, $value :=  .Values.image.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.disk }}
        volumeMounts:
          - name: {{ .Release.Name }}-data
            mountPath: {{ .Values.disk.mountPath }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.image.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.image.port }}
          initialDelaySeconds: 15
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.image.port }}
          failureThreshold: 30
          periodSeconds: 60
      {{- if .Values.disk }}
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
      {{- end }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-image-pull-secret
