{{- if .Values.backup }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-2.27.3
spec:
  schedule: {{ .Values.backup.schedule }}
  template:
    ttl: {{ .Values.backup.ttl }}
    includedNamespaces:
      - {{ .Release.Namespace }}
{{- end }}
