apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.tag }}
          imagePullPolicy: Always
          {{- if .Values.image.env }}
          env:
            {{- range $key, $value :=  .Values.image.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-image-pull-secret
